// src/frontend/svelte/components/PerfPanel.svelte
<svelte:options runes={true} />
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';

    let collapsed = $state(false);
    let domCount = $state('—');
    let mutations = $state(0);
    let heap = $state('—');
    let frame = $state('—');
    let load = $state('—');
    let ttfb = $state('—');
    let lcp = $state('—');
    let inp = $state('—');
    const fwColor = 'var(--svelte)';

    let mutCount = 0;
    let observer: MutationObserver;
    let domInt: ReturnType<typeof setInterval>;
    let heapInt: ReturnType<typeof setInterval>;
    let rafId: number;
    let lcpObserver: PerformanceObserver | undefined;
    let inpObserver: PerformanceObserver | undefined;

    onMount(() => {
        const updateDom = () => {
            domCount = document.querySelectorAll('*').length.toLocaleString();
        };
        updateDom();
        domInt = setInterval(updateDom, 2000);

        observer = new MutationObserver((mutList) => {
            const external = mutList.filter(m => {
                const el = m.target.nodeType === 1 ? m.target as Element : m.target.parentElement;
                if (!el) return false; // Ignore detached text nodes
                return !el.closest?.('.perf-panel');
            });
            if(external.length > 0) {
                mutCount += external.length;
                mutations = mutCount;
            }
        });
        observer.observe(document.body, { childList: true, subtree: true, attributes: true, characterData: true });

        const updateHeap = () => {
            const perf = performance as any;
            if (perf.memory) {
                heap = (perf.memory.usedJSHeapSize / 1048576).toFixed(1) + ' MB';
            } else {
                heap = 'N/A';
            }
        };
        updateHeap();
        heapInt = setInterval(updateHeap, 3000);

        let lastFrame = performance.now();
        const frameSamples: number[] = [];
        const frameLoop = (now: number) => {
            const delta = now - lastFrame;
            lastFrame = now;
            frameSamples.push(delta);
            if (frameSamples.length > 30) frameSamples.shift();
            const avg = frameSamples.reduce((a, b) => a + b, 0) / frameSamples.length;
            frame = avg.toFixed(1) + ' ms';
            rafId = requestAnimationFrame(frameLoop);
        };
        rafId = requestAnimationFrame(frameLoop);

        const checkLoad = () => {
            const nav = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
            if (nav) {
                if (nav.loadEventEnd > 0) {
                    load = (nav.loadEventEnd - nav.startTime).toFixed(0) + ' ms';
                }
                if (nav.responseStart > 0) {
                    ttfb = nav.responseStart.toFixed(0) + ' ms';
                }
            }
        };
        if (document.readyState === 'complete') {
            checkLoad();
        } else {
            window.addEventListener('load', checkLoad);
        }

        try {
            lcpObserver = new PerformanceObserver((entryList) => {
                const entries = entryList.getEntries();
                const lastEntry = entries[entries.length - 1];
                if (lastEntry) {
                    lcp = `${lastEntry.startTime.toFixed(0)} ms`;
                }
            });
            lcpObserver.observe({ type: 'largest-contentful-paint', buffered: true });
        } catch (e) {
            lcp = 'N/A';
        }

        let maxInp = 0;
        try {
            inpObserver = new PerformanceObserver((entryList) => {
                for (const entry of entryList.getEntries()) {
                    if (!(entry as any).interactionId) continue;
                    if (entry.duration > maxInp) {
                        maxInp = entry.duration;
                        inp = `${maxInp.toFixed(0)} ms`;
                    }
                }
            });
            inpObserver.observe({ type: 'event', durationThreshold: 16, buffered: true } as any);
        } catch (e) {
            inp = 'N/A';
        }
    });

    onDestroy(() => {
        if(typeof window === 'undefined') return;
        clearInterval(domInt);
        clearInterval(heapInt);
        if (observer) observer.disconnect();
        cancelAnimationFrame(rafId);
        if (lcpObserver) lcpObserver.disconnect();
        if (inpObserver) inpObserver.disconnect();
    });
</script>

<div class="perf-panel {collapsed ? 'perf-panel--collapsed' : ''}">
    <button class="perf-panel__toggle" title="Toggle Performance Panel" onclick={() => collapsed = !collapsed}>
        {collapsed ? '📊' : '⚡'}
    </button>
    <div class="perf-panel__body">
        <div class="perf-panel__title">Instrumentation</div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">Framework</span>
            <span class="perf-panel__value perf-panel__framework" style="color: {fwColor}">Svelte</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">DOM Nodes</span>
            <span class="perf-panel__value">{domCount}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">Mutations</span>
            <span class="perf-panel__value">{mutations.toLocaleString()}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">JS Heap</span>
            <span class="perf-panel__value">{heap}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">Frame Δ</span>
            <span class="perf-panel__value">{frame}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">Load</span>
            <span class="perf-panel__value">{load}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">TTFB</span>
            <span class="perf-panel__value">{ttfb}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">LCP</span>
            <span class="perf-panel__value">{lcp}</span>
        </div>
        <div class="perf-panel__row">
            <span class="perf-panel__label">INP</span>
            <span class="perf-panel__value">{inp}</span>
        </div>
    </div>
</div>

<style>
.perf-panel { position: fixed; bottom: var(--space-4, 16px); right: var(--space-4, 16px); z-index: 9999; font-family: var(--font-mono, monospace); font-size: var(--fs-xs, 12px); min-width: 260px; }
.perf-panel__toggle { position: absolute; top: -32px; right: 0; width: 28px; height: 28px; border: 1px solid var(--border, #333); border-radius: var(--radius-sm, 4px); background: var(--surface, #222); color: var(--text-muted, #aaa); cursor: pointer; display: flex; align-items: center; justify-content: center; font-size: 14px; transition: all var(--transition-fast, 0.2s); line-height: 1; }
.perf-panel__toggle:hover { background: var(--surface-hover, #333); color: var(--text, #fff); }
.perf-panel__body { background: var(--bg-elevated, rgba(20,20,20,0.9)); border: 1px solid var(--border, #333); border-radius: var(--radius-md, 8px); padding: var(--space-3, 12px); backdrop-filter: blur(16px); box-shadow: var(--shadow-lg, 0 10px 30px rgba(0,0,0,0.5)); }
.perf-panel__title { font-size: var(--fs-xs, 12px); font-weight: var(--fw-semibold, 600); color: var(--text-muted, #aaa); text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: var(--space-2, 8px); display: flex; align-items: center; gap: var(--space-2, 8px); }
.perf-panel__title::before { content: ''; width: 6px; height: 6px; border-radius: 50%; background: var(--success, #10b981); animation: pulse-dot 2s ease-in-out infinite; }
@keyframes pulse-dot { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
.perf-panel__row { display: flex; justify-content: space-between; align-items: center; padding: var(--space-1, 4px) 0; border-bottom: 1px solid var(--border-subtle, #222); }
.perf-panel__row:last-child { border-bottom: none; }
.perf-panel__label { color: var(--text-muted, #aaa); }
.perf-panel__value { color: var(--text, #fff); font-weight: var(--fw-medium, 500); }
.perf-panel__framework { font-weight: var(--fw-bold, 700); }
.perf-panel--collapsed .perf-panel__body { display: none; }
</style>

// src/frontend/react/components/PerfPanel.tsx
import { useState, useEffect, useRef } from 'react';

export const PerfPanel = () => {
    const [collapsed, setCollapsed] = useState(false);
    const [domCount, setDomCount] = useState<string>('—');
    const [mutations, setMutations] = useState<number>(0);
    const [heap, setHeap] = useState<string>('—');
    const [frame, setFrame] = useState<string>('—');
    const [load, setLoad] = useState<string>('—');
    const [ttfb, setTtfb] = useState<string>('—');
    const [lcp, setLcp] = useState<string>('—');
    const [inp, setInp] = useState<string>('—');
    const frameSamplesRef = useRef<number[]>([]);

    useEffect(() => {

        // DOM Count
        const updateDom = () => {
            setDomCount(document.querySelectorAll('*').length.toLocaleString());
        };
        updateDom();
        const domInt = setInterval(updateDom, 2000);

        // Mutations
        let mutCount = 0;
        const observer = new MutationObserver((mutList) => {
            console.log('[PerfPanel] MutationObserver fired with', mutList.length, 'mutations');
            const external = mutList.filter(m => {
                const el = m.target.nodeType === 1 ? m.target as Element : m.target.parentElement;
                if (!el) {
                    console.log('[PerfPanel] Ignored detached node', m.target.nodeName);
                    return false;
                }
                const isPerf = el.closest?.('.perf-panel');
                if (!isPerf) {
                    console.log('[PerfPanel] EXTERNAL MUTATION DETECTED', m.type, 'Target:', m.target.nodeName, 'el:', el.nodeName, 'class:', el.className);
                    if (m.type === 'childList') {
                        console.log('Added:', Array.from(m.addedNodes).map(n => n.nodeName), 'Removed:', Array.from(m.removedNodes).map(n => n.nodeName));
                    }
                }
                return !isPerf;
            });
            console.log('[PerfPanel] External mutations count:', external.length);
            if (external.length > 0) {
                mutCount += external.length;
                console.log('[PerfPanel] Calling setMutations', mutCount);
                setMutations(mutCount);
            }
        });
        observer.observe(document.body, { childList: true, subtree: true, attributes: true, characterData: true });

        // Heap
        const updateHeap = () => {
            const perf = performance as any;
            if (perf.memory) {
                setHeap((perf.memory.usedJSHeapSize / 1048576).toFixed(1) + ' MB');
            } else {
                setHeap('N/A');
            }
        };
        updateHeap();
        const heapInt = setInterval(updateHeap, 3000);

        // Frame — collect samples in a ref, only update state every 500ms
        let rafId: number;
        let lastFrame = performance.now();
        const samples = frameSamplesRef.current;
        samples.length = 0;
        const frameLoop = (now: number) => {
            const delta = now - lastFrame;
            lastFrame = now;
            samples.push(delta);
            if (samples.length > 30) samples.shift();
            rafId = requestAnimationFrame(frameLoop);
        };
        rafId = requestAnimationFrame(frameLoop);
        const frameInt = setInterval(() => {
            if (samples.length > 0) {
                const avg = samples.reduce((a, b) => a + b, 0) / samples.length;
                setFrame(avg.toFixed(1) + ' ms');
            }
        }, 500);

        // Load
        const checkLoad = () => {
            const nav = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
            if (nav) {
                if (nav.loadEventEnd > 0) {
                    setLoad((nav.loadEventEnd - nav.startTime).toFixed(0) + ' ms');
                }
                if (nav.responseStart > 0) {
                    setTtfb(nav.responseStart.toFixed(0) + ' ms');
                }
            }
        };
        if (document.readyState === 'complete') {
            checkLoad();
        } else {
            window.addEventListener('load', checkLoad);
        }

        // LCP
        let lcpObserver: PerformanceObserver | undefined;
        try {
            lcpObserver = new PerformanceObserver((entryList) => {
                const entries = entryList.getEntries();
                const lastEntry = entries[entries.length - 1];
                if (lastEntry) {
                    setLcp(`${lastEntry.startTime.toFixed(0)} ms`);
                }
            });
            lcpObserver.observe({ type: 'largest-contentful-paint', buffered: true });
        } catch (e) {
            setLcp('N/A');
        }

        // INP
        let maxInp = 0;
        let inpObserver: PerformanceObserver | undefined;
        try {
            inpObserver = new PerformanceObserver((entryList) => {
                for (const entry of entryList.getEntries()) {
                    if (!(entry as any).interactionId) continue;
                    if (entry.duration > maxInp) {
                        maxInp = entry.duration;
                        setInp(`${maxInp.toFixed(0)} ms`);
                    }
                }
            });
            inpObserver.observe({ type: 'event', durationThreshold: 16, buffered: true } as any);
        } catch (e) {
            setInp('N/A');
        }

        return () => {
            clearInterval(domInt);
            clearInterval(heapInt);
            clearInterval(frameInt);
            observer.disconnect();
            cancelAnimationFrame(rafId);
            if (lcpObserver) lcpObserver.disconnect();
            if (inpObserver) inpObserver.disconnect();
            window.removeEventListener('load', checkLoad);
        };
    }, []);

    const fwColor = 'var(--react)';

    const PERF_CSS = `
.perf-panel { position: fixed; bottom: var(--space-4, 16px); right: var(--space-4, 16px); z-index: 9999; font-family: var(--font-mono, monospace); font-size: var(--fs-xs, 12px); min-width: 260px; }
.perf-panel__toggle { position: absolute; top: -32px; right: 0; width: 28px; height: 28px; border: 1px solid var(--border, #333); border-radius: var(--radius-sm, 4px); background: var(--surface, #222); color: var(--text-muted, #aaa); cursor: pointer; display: flex; align-items: center; justify-content: center; font-size: 14px; transition: all var(--transition-fast, 0.2s); line-height: 1; }
.perf-panel__toggle:hover { background: var(--surface-hover, #333); color: var(--text, #fff); }
.perf-panel__body { background: var(--bg-elevated, rgba(20,20,20,0.9)); border: 1px solid var(--border, #333); border-radius: var(--radius-md, 8px); padding: var(--space-3, 12px); backdrop-filter: blur(16px); box-shadow: var(--shadow-lg, 0 10px 30px rgba(0,0,0,0.5)); }
.perf-panel__title { font-size: var(--fs-xs, 12px); font-weight: var(--fw-semibold, 600); color: var(--text-muted, #aaa); text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: var(--space-2, 8px); display: flex; align-items: center; gap: var(--space-2, 8px); }
.perf-panel__title::before { content: ''; width: 6px; height: 6px; border-radius: 50%; background: var(--success, #10b981); animation: pulse-dot 2s ease-in-out infinite; }
@keyframes pulse-dot { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
.perf-panel__row { display: flex; justify-content: space-between; align-items: center; padding: var(--space-1, 4px) 0; border-bottom: 1px solid var(--border-subtle, #222); }
.perf-panel__row:last-child { border-bottom: none; }
.perf-panel__label { color: var(--text-muted, #aaa); }
.perf-panel__value { color: var(--text, #fff); font-weight: var(--fw-medium, 500); }
.perf-panel__framework { font-weight: var(--fw-bold, 700); }
.perf-panel--collapsed .perf-panel__body { display: none; }
    `;

    return (
            <div className={`perf-panel ${collapsed ? 'perf-panel--collapsed' : ''}`}>
                <style dangerouslySetInnerHTML={{ __html: PERF_CSS }} />
                <button className="perf-panel__toggle" title="Toggle Performance Panel" onClick={() => setCollapsed(!collapsed)}>
                    {collapsed ? '📊' : '⚡'}
                </button>
                <div className="perf-panel__body">
                    <div className="perf-panel__title">Instrumentation</div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">Framework</span>
                        <span className="perf-panel__value perf-panel__framework" style={{ color: fwColor }}>React</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">DOM Nodes</span>
                        <span className="perf-panel__value">{domCount}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">Mutations</span>
                        <span className="perf-panel__value">{mutations.toLocaleString()}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">JS Heap</span>
                        <span className="perf-panel__value">{heap}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">Frame Δ</span>
                        <span className="perf-panel__value">{frame}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">Load</span>
                        <span className="perf-panel__value">{load}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">TTFB</span>
                        <span className="perf-panel__value">{ttfb}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">LCP</span>
                        <span className="perf-panel__value">{lcp}</span>
                    </div>
                    <div className="perf-panel__row">
                        <span className="perf-panel__label">INP</span>
                        <span className="perf-panel__value">{inp}</span>
                    </div>
                </div>
            </div>
    );
};
